<a href="https://colab.research.google.com/github/SDB016/Study/blob/main/Pytorch/Softmax_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
torch.manual_seed(1)

In [ ]:
z = torch.FloatTensor([1,2,3])

In [ ]:
hypothesis = F.softmax(z, dim = 0) # F.max(z, dim = 0) >>>> ([0,0,1])
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [ ]:
hypothesis.sum()

tensor(1.)

# **Cross Entropy Loss ( Low-level)**

In [ ]:
z = torch.rand(3,5,requires_grad=True)
hypothesis = F.softmax(z, dim = 1)
print(hypothesis)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward>)


In [ ]:
y = torch.randint(5,(3,)).long()
print(y)

tensor([0, 2, 1])
