<a href="https://colab.research.google.com/github/SDB016/Study/blob/main/Pytorch/torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **numpy VS pytorch**

# numpy

In [1]:
import numpy as np
import torch

In [2]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print(t.ndim)
print(t.shape)

1
(7,)


In [7]:
t = np.array([[0.,1.,2.],[3.,4.,5.]])
print(t)

[[0. 1. 2.]
 [3. 4. 5.]]


In [8]:
print(t.ndim)
print(t.shape)

2
(2, 3)


# pytorch

In [9]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [11]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [12]:
t = torch.FloatTensor([[0.,1.,2.],[3.,4.,5.]])
print(t)

tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [13]:
print(t.dim())
print(t.shape)
print(t.size())

2
torch.Size([2, 3])
torch.Size([2, 3])


# **Broadcasting**

In [14]:
#Same dim
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,3])
print(m1+m2)

tensor([5., 6.])


In [16]:
#Vector + Scalar
m1 = torch.FloatTensor([3,3,4])
m2 = torch.FloatTensor([2]) # torch.FloatTensor([2,2,2])
print(m1+m2)

tensor([5., 5., 6.])


In [18]:
#2x1 vector + 1x2 vector
m1 = torch.FloatTensor([[3,3]]) #torch.FloatTensor([[3,3],[3,3]])
m2 = torch.FloatTensor([[2],[3]])#torch.FloatTensor([[2,2],[3,3]])
print(m1+m2)

tensor([[5., 5.],
        [6., 6.]])


# **Mean**

In [19]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [21]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [22]:
print(t.mean())
print(t.mean(dim = 0))
print(t.mean(dim = 1))
print(t.mean(dim = -1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


# **SUM**

In [23]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [24]:
print(t.sum())
print(t.sum(dim = 0))
print(t.sum(dim = 1))
print(t.sum(dim = -1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


# **MAX & Argmax**

In [25]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [26]:
print(t.max())

tensor(4.)


In [27]:
print(t.max(dim = 0))
print('Max: ', t.max(dim = 0)[0])
print('Argmax: ', t.max(dim = 0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


# **View (Reshape)**

In [30]:
t = np.array([[[0,1,2],
               [3,4,5]],
              [[6,7,8],
              [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [31]:
print(ft.view([-1,3])) #I don't know the first variable,but the second is 3
print(ft.view([-1,3]).shape) #(2,2,3) -> (2x2,3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [32]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape) 

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


# **Squeeze**

In [34]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft.shape)

torch.Size([3, 1])


In [35]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


# **Unsqueeze**

In [36]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [37]:
print(ft.unsqueeze(0)) #dim = 0
print(ft.unsqueeze(0).shape) # insert 1 to index 0

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [38]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [39]:
print(ft.unsqueeze(1)) #dim = 1
print(ft.unsqueeze(1).shape) # insert 1 to index 1

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [41]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape) # insert 1 to index -1 (last index)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


# **Type Casting**

In [42]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [43]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [45]:
bt = torch.ByteTensor([True,False,True,True])
print(bt)

tensor([1, 0, 1, 1], dtype=torch.uint8)


# **Concatenate**

In [46]:
x = torch.Tensor([[1,2],[3,4]])
y = torch.Tensor([[3,4],[5,6]])

In [49]:
print(torch.cat([x,y],dim = 0))
print(torch.cat([x,y],dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 2., 3., 4.],
        [3., 4., 5., 6.]])


# **Stacking**

In [50]:
x = torch.Tensor([1,2])
y = torch.Tensor([3,4])
z = torch.Tensor([5,6])

In [52]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 3., 5.],
        [2., 4., 6.]])


In [53]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0),z.unsqueeze(0)],dim = 0)) #print(torch.stack([x,y,z]))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


# **Ones and Zeros**

In [54]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [55]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# **In-place Operation**

In [56]:
x = torch.FloatTensor([[1,2],[3,4]])

In [58]:
print(x.mul(2.))
print(x)

print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


출처: https://github.com/deeplearningzerotoall/PyTorch/blob/master